version: "3.7"

services:
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: root
      POSTGRES_DB: tasktracker
    volumes:
      - ./db/postgresql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"